export const logInData = [
  {
    id: 0,
    type: "text",
    name: "user_name",
    value: "",
    errorMsg: "Please enter your full name",
    icon: false,
    label: "",
    required: false,
    isRequiredFailed: false,
    validation: true,
    dropdown: false,
    placeholder: "Full Name *",
    autoComplete: false,
    validationEnabled: { required: true, min: 2 },
  },
  {
    id: 1,
    type: "email",
    name: "email",
    value: "",
    label: "",
    errorMsg: "Please enter a valid email address",
    icon: false,
    required: false,
    isRequiredFailed: false,
    validationEnabled: { required: true, pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/ },
    validation: true,
    dropdown: false,
    placeholder: "Email *",
    autoComplete: false,
  },
  {
    id: 2,
    label: "",
    name: "password",
    value: "",
    errorMsg: "Password must be at least 8 characters & contain at least one special character, letter, one Capital letter and digit",
    icon: true,
    type: "password",
    required: false,
    isRequiredFailed: false,
    validationEnabled: { required: true, pattern: /^(?=.*[!@#$%^&*(),.?":{}|<>])(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{6,}$/ },
    validation: true,
    placeholder: "Password *",
    autoComplete: false,
  },
  {
    id: 3,
    label: "",
    type: "password",
    name: "confirmPassword",
    value: "",
    errorMsg: "Password is not matching",
    icon: true,
    required: false,
    isRequiredFailed: false,
    validationEnabled: {
      required: true,
      minLength: 8,
      validate: (value: any, values: { password: any }) => value === values.password,
    },
    validation: true,
    placeholder: "Confirm Password *",
    autoComplete: false,
  },
];

export const SignInData = [
  {
    id: 0,
    type: "email",
    name: "email",
    value: "",
    label: "",
    icon: false,
    required: false,
    //errorMsg: "Please enter a valid email address",
    isRequiredFailed: false,
    validationEnabled: { required: true, pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/ },
    validation: false,
    dropdown: false,
    placeholder: "Email",
    autoComplete: false,
  },
  {
    id: 1,
    type: "password",
    name: "password",
    value: "",
    label: "",
    errorMsg: "Password must be at least 8 characters & contain at least one special character, letter, one Capital letter and digit",
    icon: true,
    required: false,
    isRequiredFailed: false,
    validationEnabled: { required: true, pattern: /^(?=.*[!@#$%^&*(),.?":{}|<>])(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{6,}$/ },
    validation: false,
    placeholder: "Password",
    autoComplete: false,
  },
];

export const resetPassword = [
  {
    id: 0,
    type: "password",
    name: "password",
    value: "",
    label: "",
    icon: true,
    required: false,
    errorMsg: "Password must be at least 8 characters & contain at least one special character, letter, one Capital letter and digit",
    isRequiredFailed: false,
    validation: false,
    dropdown: false,
    placeholder: "Password",
    autoComplete: false,
    validationEnabled: { required: true, pattern: /^(?=.*[!@#$%^&*(),.?":{}|<>])(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{6,}$/ },
  },
  {
    id: 1,
    type: "password",
    name: "confirm-password",
    value: "",
    label: "",
    errorMsg: "Password is not matching",
    icon: true,
    required: false,
    isRequiredFailed: false,
    validationEnabled: {
      required: true,
      minLength: 8,
      validate: (value: any, values: { password: any }) => value === values.password,
    },
    validation: false,
    placeholder: "Confirm Password",
    autoComplete: false,
  },
];
