
//SIGNUP
export const GET_SIGNUP_REQUEST = "GET_SIGNUP_REQUEST";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const MAKE_NEW_SIGNUP = "MAKE_NEW_SIGNUP";

//EMAIL VERIFICATION
export const GET_EMAIL_VERIFICATION_REQUEST = "GET_EMAIL_VERIFICATION_REQUEST";
export const GET_EMAIL_VERIFICATION_SUCCESS = "GET_EMAIL_VERIFICATION_SUCCESS";

// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_RESULT_EMPTY = "FORGOT_PASSWORD_RESULT_EMPTY";

//RESET PASSWORD
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";


